name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Checkout second tools
        uses: actions/checkout@v4
        with:
          repository: Shobitm/nodejsNew1
          path: nodejsNew1

      - name: run shell script
        run: |
          ls -la
          pwd
          ls -la ..
          ls -la  ../..
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Running Tests
        run: |
          pwd
          echo "Running Tests"