name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Checkout second tools
        uses: actions/checkout@v4
        with:
          repository: Shobitm/nodejsNew1
          path: nodejsNew1

      - name: run shell script
        run: |
          ls -la
          pwd
          ls -la ..
          ls -la  ../..
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          path: main
      
      - name: Running Tests
        run: |
          pwd
          echo "Running Tests"
  push:
    runs-on: ubuntu-latest
    needs: 
      - test
      - build
    steps:
      - name: Pushing Docker Image to Google Docker Registry
        run: |
          pwd
          echo "Pushing to Docker Registry"
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    needs: push
    steps:
      - name: Deploying to Dev Environment
        run: |
          pwd
          echo "Deploying to Dev"
  deploy-uat:
    runs-on: ubuntu-latest
    environment: uat
    needs: deploy-dev
    steps:
      - name: Deploying to UAT Environment
        run: |
          pwd
          echo "Deploying to UAT"
  deploy-prod:
    runs-on: ubuntu-latest
    environment: prod
    needs: deploy-uat
    steps:
      - name: Deploying to Prod Environment
        run: |
          pwd
          echo "Deploying to Prod1"
